const routes = {
  //header
  home: '/',
  login: '/login',
  loginSuccess: '/login-success/:id',
  detailItem: '/detailItem/:id',
  detailBlog: '/detailBlog/:id',
  detailForum: '/detailForum/:id',
  allProducts: '/allProducts',
  adminPending: '/adminPending',
  adminWaiting: '/adminWaiting',
  adminDelivering: '/adminDelivering',
  adminSuccess: '/adminSuccess',
  appointment: '/appointment',
  appointmentPending: '/appointmentPending',
  appointmentAccepted: '/appointmentAccepted',
  appointmentCanceled: '/appointmentCanceled',
  appointmentCompleted: '/appointmentCompleted',
  manageBrand: '/manageBrand',
  manageBreeds: '/manageBreeds',
  manageProducts: '/manageProducts',
  manageServices: '/manageServices',
  historyOrderPending: '/historyOrderPending',
  historyOrderWaiting: '/historyOrderWaiting',
  historyOrderDelivering: '/historyOrderDelivering',
  historyOrderSuccess: '/historyOrderSuccess',
  historyOrderCanceled: '/historyOrderCanceled',
  historyAppointmentPending: '/historyAppointmentPending',
  historyAppointmentAccepted: '/historyAppointmentAccepted',
  historyAppointmentCanceled: '/historyAppointmentCanceled',
  historyAppointmentFinished: '/historyAppointmentFinished',
  bookingAppointment: '/bookingAppointment',
  historyDetails: '/historyDetails',
  manageBlog: '/manageBlog',
  blog: '/blog',
  forum: '/forum',
  addBlog: '/addBlog',
  createPost: '/createPost',
  revenue: '/revenue',
  information: '/information',
  history: '/history',
  appointmentHistory: '/appointmentHistory',
  historyPending: 'historyPending',
  cart: '/cart',
  checkout: '/checkout',
  contact: '/contact'
};

export default routes;
