const routes = {
  //header
  home: '/',
  login: '/login',
  detailItem: '/detailItem/:id',
  allProducts: '/allProducts',
  adminPending: '/adminPending',
  adminWaiting: '/adminWaiting',
  adminDelivering: '/adminDelivering',
  adminSuccess: '/adminSuccess',
  appointment: '/appointment',
  appointmentPending: '/appointmentPending',
  appointmentAccepted: '/appointmentAccepted',
  appointmentCanceled: '/appointmentCanceled',
  manageBrand: '/manageBrand',
  manageBreeds: '/manageBreeds',
  manageProducts: '/manageProducts',
  manageServices: '/manageServices',
  orderPending: '/orderPending',
  orderWaiting: '/orderWaiting',
  orderDelivering: '/orderDelivering',
  orderSuccess: '/orderSuccess',
  orderCanceled: '/orderCanceled',
  historyAppointmentPending: '/historyAppointmentPending',
  historyAppointmentAccepted: '/historyAppointmentAccepted',
  historyAppointmentCanceled: '/historyAppointmentCanceled',
  historyAppointmentFinished: '/historyAppointmentFinished',
  revenue: '/revenue',
  information: '/information',
  history: '/history',
  appointmentHistory: '/appointmentHistory',
  historyPending: 'historyPending',
  cart: '/cart',
  checkout: '/checkout',
  introduce: '/introduce',
  contact: '/contact'
};

export default routes;
